# Generated by Django 4.1.7 on 2023-03-27 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaqSection",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=10)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("order", models.IntegerField(default=10)),
                ("active", models.BooleanField(default=True)),
                ("question", models.TextField()),
                ("short_answer", models.TextField()),
                ("answer", models.TextField()),
                (
                    "section_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="beamz_website.faqsection",
                    ),
                ),
            ],
        ),
    ]
