# Generated by Django 5.1.7 on 2025-04-11 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamz_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('name_fr', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='short_answer_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faqsection',
            name='name_fr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('published', models.BooleanField(default=False)),
                ('publication_date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=250)),
                ('title_fr', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(help_text='Short description of the blog post')),
                ('description_fr', models.TextField(blank=True)),
                ('content', models.TextField(help_text='Full content of the blog post')),
                ('content_fr', models.TextField(blank=True)),
                ('blog_img', models.ImageField(blank=True, upload_to='blog/articles/')),
                ('tags', models.ManyToManyField(blank=True, related_name='blogs', to='beamz_website.blogtag')),
            ],
        ),
    ]
