# Generated by Django 5.2 on 2025-04-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamz_website', '0002_blogtag_faq_answer_fr_faq_question_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
