# Generated by Django 5.2 on 2025-04-27 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamz_website', '0003_alter_blogpost_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPicture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('picture', models.ImageField(upload_to='blog/articles/pictures/')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='beamz_website.blogpost')),
            ],
        ),
    ]
