# Generated by Django 5.2.1 on 2025-06-17 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamz_website', '0004_blogpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('planned', models.DateField()),
                ('template', models.CharField(choices=[('basic', 'Basic')], default='basic', max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MailingRecipient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('sent', models.BooleanField(default=False)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='beamz_website.mailing')),
            ],
        ),
    ]
